server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/localtest
    username: root
    password: root

mybatis:
  mapper-locations: mapper/*.xml
